// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weixin.proto

package com.fan.xc.boot.plugins.weixin.grpc;

public final class WeiXinProto {
  private WeiXinProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014weixin.proto\032\033google/protobuf/empty.pr" +
      "oto\032\036google/protobuf/wrappers.proto2\240\001\n\r" +
      "WeiXinService\022H\n\016getAccessToken\022\026.google" +
      ".protobuf.Empty\032\034.google.protobuf.String" +
      "Value\"\000\022E\n\013getJsTicket\022\026.google.protobuf" +
      ".Empty\032\034.google.protobuf.StringValue\"\000B4" +
      "\n#com.fan.xc.boot.plugins.weixin.grpcB\013W" +
      "eiXinProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
